CREATE SCHEMA IF NOT EXISTS stg;
CREATE SCHEMA IF NOT EXISTS reg;
CREATE SCHEMA IF NOT EXISTS ods;
CREATE SCHEMA IF NOT EXISTS dm;

COMMENT ON SCHEMA reg IS 'Registry';
COMMENT ON SCHEMA stg IS 'Staging';
COMMENT ON SCHEMA ods IS 'Operational data store';
COMMENT ON SCHEMA dm IS 'Data marts';