create table if not exists stg.taxi_data (
    id serial primary key,
    vendor_id varchar,
    tpep_pickup varchar,
    tpep_dropoff varchar,
    passenger_count varchar,
    trip_distance varchar,
    ratecode_id varchar,
    store_and_forward varchar,
    pu_location_id varchar,
    do_location_id varchar,
    payment_type varchar,
    fare varchar,
    extras varchar,
    mta_tax varchar,
    tip varchar,
    tolls varchar,
    improvement varchar,
    total varchar,
    congestion varchar,
    airport_fee varchar,
    cbd_congestion_fee varchar
    );