CREATE TABLE if NOT EXISTS stg.taxi_data (
    id serial PRIMARY KEY,
    vendor_id VARCHAR,
    tpep_pickup VARCHAR,
    tpep_dropoff VARCHAR,
    passenger_count VARCHAR,
    trip_distance VARCHAR,
    ratecode_id VARCHAR,
    store_and_forward VARCHAR,
    pu_location_id VARCHAR,
    do_location_id VARCHAR,
    payment_type VARCHAR,
    fare VARCHAR,
    extras VARCHAR,
    mta_tax VARCHAR,
    tip VARCHAR,
    tolls VARCHAR,
    improvement VARCHAR,
    total VARCHAR,
    congestion VARCHAR,
    airport_fee VARCHAR,
    cbd_congestion_fee VARCHAR
    );